export enum Onramps {
  Onramp,
  None,
}

export default [
  {
    label: "Afghanistan",
    value: "AF",
    phoneCode: "+93",
    currency: "AFN",
    onramp: Onramps.None,
  },
  {
    label: "Albania",
    value: "AL",
    phoneCode: "+355",
    currency: "ALL",
    onramp: Onramps.None,
  },
  {
    label: "Algeria",
    value: "DZ",
    phoneCode: "+213",
    currency: "DZD",
    onramp: Onramps.None,
  },
  {
    label: "Andorra",
    value: "AD",
    phoneCode: "+376",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Angola",
    value: "AO",
    phoneCode: "+244",
    currency: "AOA",
    onramp: Onramps.None,
  },
  {
    label: "Antigua and Barbuda",
    value: "AG",
    phoneCode: "+1-268",
    currency: "XCD",
    onramp: Onramps.None,
  },
  {
    label: "Argentina",
    value: "AR",
    phoneCode: "+54",
    currency: "ARS",
    onramp: Onramps.None,
  },
  {
    label: "Armenia",
    value: "AM",
    phoneCode: "+374",
    currency: "AMD",
    onramp: Onramps.None,
  },
  {
    label: "Australia",
    value: "AU",
    phoneCode: "+61",
    currency: "AUD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Austria",
    value: "AT",
    phoneCode: "+43",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Azerbaijan",
    value: "AZ",
    phoneCode: "+994",
    currency: "AZN",
    onramp: Onramps.None,
  },
  {
    label: "Bahamas",
    value: "BS",
    phoneCode: "+1-242",
    currency: "BSD",
    onramp: Onramps.None,
  },
  {
    label: "Bahrain",
    value: "BH",
    phoneCode: "+973",
    currency: "BHD",
    onramp: Onramps.None,
  },
  {
    label: "Bangladesh",
    value: "BD",
    phoneCode: "+880",
    currency: "BDT",
    onramp: Onramps.None,
  },
  {
    label: "Barbados",
    value: "BB",
    phoneCode: "+1-246",
    currency: "BBD",
    onramp: Onramps.None,
  },
  {
    label: "Belarus",
    value: "BY",
    phoneCode: "+375",
    currency: "BYN",
    onramp: Onramps.None,
  },
  {
    label: "Belgium",
    value: "BE",
    phoneCode: "+32",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Belize",
    value: "BZ",
    phoneCode: "+501",
    currency: "BZD",
    onramp: Onramps.None,
  },
  {
    label: "Benin",
    value: "BJ",
    phoneCode: "+229",
    currency: "XOF",
    onramp: Onramps.None,
  },
  {
    label: "Bhutan",
    value: "BT",
    phoneCode: "+975",
    currency: "BTN",
    onramp: Onramps.None,
  },
  {
    label: "Bolivia",
    value: "BO",
    phoneCode: "+591",
    currency: "BOB",
    onramp: Onramps.None,
  },
  {
    label: "Bosnia and Herzegovina",
    value: "BA",
    phoneCode: "+387",
    currency: "BAM",
    onramp: Onramps.None,
  },
  {
    label: "Botswana",
    value: "BW",
    phoneCode: "+267",
    currency: "BWP",
    onramp: Onramps.None,
  },
  {
    label: "Brazil",
    value: "BR",
    phoneCode: "+55",
    currency: "BRL",
    onramp: Onramps.Onramp,
  },
  {
    label: "Brunei",
    value: "BN",
    phoneCode: "+673",
    currency: "BND",
    onramp: Onramps.None,
  },
  {
    label: "Bulgaria",
    value: "BG",
    phoneCode: "+359",
    currency: "BGN",
    onramp: Onramps.None,
  },
  {
    label: "Burkina Faso",
    value: "BF",
    phoneCode: "+226",
    currency: "XOF",
    onramp: Onramps.None,
  },
  {
    label: "Burundi",
    value: "BI",
    phoneCode: "+257",
    currency: "BIF",
    onramp: Onramps.None,
  },
  {
    label: "Cabo Verde",
    value: "CV",
    phoneCode: "+238",
    currency: "CVE",
    onramp: Onramps.None,
  },
  {
    label: "Cambodia",
    value: "KH",
    phoneCode: "+855",
    currency: "KHR",
    onramp: Onramps.None,
  },
  {
    label: "Cameroon",
    value: "CM",
    phoneCode: "+237",
    currency: "XAF",
    onramp: Onramps.None,
  },
  {
    label: "Canada",
    value: "CA",
    phoneCode: "+1",
    currency: "CAD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Central African Republic",
    value: "CF",
    phoneCode: "+236",
    currency: "XAF",
    onramp: Onramps.None,
  },
  {
    label: "Chad",
    value: "TD",
    phoneCode: "+235",
    currency: "XAF",
    onramp: Onramps.None,
  },
  {
    label: "Chile",
    value: "CL",
    phoneCode: "+56",
    currency: "CLP",
    onramp: Onramps.None,
  },
  {
    label: "China",
    value: "CN",
    phoneCode: "+86",
    currency: "CNY",
    onramp: Onramps.None,
  },
  {
    label: "Colombia",
    value: "CO",
    phoneCode: "+57",
    currency: "COP",
    onramp: Onramps.None,
  },
  {
    label: "Comoros",
    value: "KM",
    phoneCode: "+269",
    currency: "KMF",
    onramp: Onramps.None,
  },
  {
    label: "Congo (Congo-Brazzaville)",
    value: "CG",
    phoneCode: "+242",
    currency: "XAF",
    onramp: Onramps.None,
  },
  {
    label: "Congo (DRC)",
    value: "CD",
    phoneCode: "+243",
    currency: "CDF",
    onramp: Onramps.None,
  },
  {
    label: "Costa Rica",
    value: "CR",
    phoneCode: "+506",
    currency: "CRC",
    onramp: Onramps.None,
  },
  {
    label: "Croatia",
    value: "HR",
    phoneCode: "+385",
    currency: "HRK",
    onramp: Onramps.None,
  },
  {
    label: "Cuba",
    value: "CU",
    phoneCode: "+53",
    currency: "CUP",
    onramp: Onramps.None,
  },
  {
    label: "Cyprus",
    value: "CY",
    phoneCode: "+357",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Czechia",
    value: "CZ",
    phoneCode: "+420",
    currency: "CZK",
    onramp: Onramps.None,
  },
  {
    label: "Denmark",
    value: "DK",
    phoneCode: "+45",
    currency: "DKK",
    onramp: Onramps.Onramp,
  },
  {
    label: "Djibouti",
    value: "DJ",
    phoneCode: "+253",
    currency: "DJF",
    onramp: Onramps.None,
  },
  {
    label: "Dominica",
    value: "DM",
    phoneCode: "+1-767",
    currency: "XCD",
    onramp: Onramps.None,
  },
  {
    label: "Dominican Republic",
    value: "DO",
    phoneCode: "+1-809",
    currency: "DOP",
    onramp: Onramps.None,
  },
  {
    label: "Ecuador",
    value: "EC",
    phoneCode: "+593",
    currency: "USD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Egypt",
    value: "EG",
    phoneCode: "+20",
    currency: "EGP",
    onramp: Onramps.None,
  },
  {
    label: "El Salvador",
    value: "SV",
    phoneCode: "+503",
    currency: "USD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Equatorial Guinea",
    value: "GQ",
    phoneCode: "+240",
    currency: "XAF",
    onramp: Onramps.None,
  },
  {
    label: "Eritrea",
    value: "ER",
    phoneCode: "+291",
    currency: "ERN",
    onramp: Onramps.None,
  },
  {
    label: "Estonia",
    value: "EE",
    phoneCode: "+372",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Eswatini",
    value: "SZ",
    phoneCode: "+268",
    currency: "SZL",
    onramp: Onramps.None,
  },
  {
    label: "Ethiopia",
    value: "ET",
    phoneCode: "+251",
    currency: "ETB",
    onramp: Onramps.None,
  },
  {
    label: "Fiji",
    value: "FJ",
    phoneCode: "+679",
    currency: "FJD",
    onramp: Onramps.None,
  },
  {
    label: "Finland",
    value: "FI",
    phoneCode: "+358",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "France",
    value: "FR",
    phoneCode: "+33",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Gabon",
    value: "GA",
    phoneCode: "+241",
    currency: "XAF",
    onramp: Onramps.None,
  },
  {
    label: "Gambia",
    value: "GM",
    phoneCode: "+220",
    currency: "GMD",
    onramp: Onramps.None,
  },
  {
    label: "Georgia",
    value: "GE",
    phoneCode: "+995",
    currency: "GEL",
    onramp: Onramps.None,
  },
  {
    label: "Germany",
    value: "DE",
    phoneCode: "+49",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Ghana",
    value: "GH",
    phoneCode: "+233",
    currency: "GHS",
    onramp: Onramps.None,
  },
  {
    label: "Greece",
    value: "GR",
    phoneCode: "+30",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Grenada",
    value: "GD",
    phoneCode: "+1-473",
    currency: "XCD",
    onramp: Onramps.None,
  },
  {
    label: "Guatemala",
    value: "GT",
    phoneCode: "+502",
    currency: "GTQ",
    onramp: Onramps.None,
  },
  {
    label: "Guinea",
    value: "GN",
    phoneCode: "+224",
    currency: "GNF",
    onramp: Onramps.None,
  },
  {
    label: "Guinea-Bissau",
    value: "GW",
    phoneCode: "+245",
    currency: "XOF",
    onramp: Onramps.None,
  },
  {
    label: "Guyana",
    value: "GY",
    phoneCode: "+592",
    currency: "GYD",
    onramp: Onramps.None,
  },
  {
    label: "Haiti",
    value: "HT",
    phoneCode: "+509",
    currency: "HTG",
    onramp: Onramps.None,
  },
  {
    label: "Honduras",
    value: "HN",
    phoneCode: "+504",
    currency: "HNL",
    onramp: Onramps.None,
  },
  {
    label: "Hungary",
    value: "HU",
    phoneCode: "+36",
    currency: "HUF",
    onramp: Onramps.None,
  },
  {
    label: "Iceland",
    value: "IS",
    phoneCode: "+354",
    currency: "ISK",
    onramp: Onramps.None,
  },
  {
    label: "India",
    value: "IN",
    phoneCode: "+91",
    currency: "INR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Indonesia",
    value: "ID",
    phoneCode: "+62",
    currency: "IDR",
    onramp: Onramps.None,
  },
  {
    label: "Iran",
    value: "IR",
    phoneCode: "+98",
    currency: "IRR",
    onramp: Onramps.None,
  },
  {
    label: "Iraq",
    value: "IQ",
    phoneCode: "+964",
    currency: "IQD",
    onramp: Onramps.None,
  },
  {
    label: "Ireland",
    value: "IE",
    phoneCode: "+353",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Israel",
    value: "IL",
    phoneCode: "+972",
    currency: "ILS",
    onramp: Onramps.None,
  },
  {
    label: "Italy",
    value: "IT",
    phoneCode: "+39",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Jamaica",
    value: "JM",
    phoneCode: "+1-876",
    currency: "JMD",
    onramp: Onramps.None,
  },
  {
    label: "Japan",
    value: "JP",
    phoneCode: "+81",
    currency: "JPY",
    onramp: Onramps.Onramp,
  },
  {
    label: "Jordan",
    value: "JO",
    phoneCode: "+962",
    currency: "JOD",
    onramp: Onramps.None,
  },
  {
    label: "Kazakhstan",
    value: "KZ",
    phoneCode: "+7",
    currency: "KZT",
    onramp: Onramps.None,
  },
  {
    label: "Kenya",
    value: "KE",
    phoneCode: "+254",
    currency: "KES",
    onramp: Onramps.None,
  },
  {
    label: "Kiribati",
    value: "KI",
    phoneCode: "+686",
    currency: "AUD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Kuwait",
    value: "KW",
    phoneCode: "+965",
    currency: "KWD",
    onramp: Onramps.None,
  },
  {
    label: "Kyrgyzstan",
    value: "KG",
    phoneCode: "+996",
    currency: "KGS",
    onramp: Onramps.None,
  },
  {
    label: "Laos",
    value: "LA",
    phoneCode: "+856",
    currency: "LAK",
    onramp: Onramps.None,
  },
  {
    label: "Latvia",
    value: "LV",
    phoneCode: "+371",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Lebanon",
    value: "LB",
    phoneCode: "+961",
    currency: "LBP",
    onramp: Onramps.None,
  },
  {
    label: "Lesotho",
    value: "LS",
    phoneCode: "+266",
    currency: "LSL",
    onramp: Onramps.None,
  },
  {
    label: "Liberia",
    value: "LR",
    phoneCode: "+231",
    currency: "LRD",
    onramp: Onramps.None,
  },
  {
    label: "Libya",
    value: "LY",
    phoneCode: "+218",
    currency: "LYD",
    onramp: Onramps.None,
  },
  {
    label: "Liechtenstein",
    value: "LI",
    phoneCode: "+423",
    currency: "CHF",
    onramp: Onramps.None,
  },
  {
    label: "Lithuania",
    value: "LT",
    phoneCode: "+370",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Luxembourg",
    value: "LU",
    phoneCode: "+352",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Madagascar",
    value: "MG",
    phoneCode: "+261",
    currency: "MGA",
    onramp: Onramps.None,
  },
  {
    label: "Malawi",
    value: "MW",
    phoneCode: "+265",
    currency: "MWK",
    onramp: Onramps.None,
  },
  {
    label: "Malaysia",
    value: "MY",
    phoneCode: "+60",
    currency: "MYR",
    onramp: Onramps.None,
  },
  {
    label: "Maldives",
    value: "MV",
    phoneCode: "+960",
    currency: "MVR",
    onramp: Onramps.None,
  },
  {
    label: "Mali",
    value: "ML",
    phoneCode: "+223",
    currency: "XOF",
    onramp: Onramps.None,
  },
  {
    label: "Malta",
    value: "MT",
    phoneCode: "+356",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Marshall Islands",
    value: "MH",
    phoneCode: "+692",
    currency: "USD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Mauritania",
    value: "MR",
    phoneCode: "+222",
    currency: "MRU",
    onramp: Onramps.None,
  },
  {
    label: "Mauritius",
    value: "MU",
    phoneCode: "+230",
    currency: "MUR",
    onramp: Onramps.None,
  },
  {
    label: "Mexico",
    value: "MX",
    phoneCode: "+52",
    currency: "MXN",
    onramp: Onramps.Onramp,
  },
  {
    label: "Micronesia",
    value: "FM",
    phoneCode: "+691",
    currency: "USD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Moldova",
    value: "MD",
    phoneCode: "+373",
    currency: "MDL",
    onramp: Onramps.None,
  },
  {
    label: "Monaco",
    value: "MC",
    phoneCode: "+377",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Mongolia",
    value: "MN",
    phoneCode: "+976",
    currency: "MNT",
    onramp: Onramps.None,
  },
  {
    label: "Montenegro",
    value: "ME",
    phoneCode: "+382",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Morocco",
    value: "MA",
    phoneCode: "+212",
    currency: "MAD",
    onramp: Onramps.None,
  },
  {
    label: "Mozambique",
    value: "MZ",
    phoneCode: "+258",
    currency: "MZN",
    onramp: Onramps.None,
  },
  {
    label: "Myanmar",
    value: "MM",
    phoneCode: "+95",
    currency: "MMK",
    onramp: Onramps.None,
  },
  {
    label: "Namibia",
    value: "NA",
    phoneCode: "+264",
    currency: "NAD",
    onramp: Onramps.None,
  },
  {
    label: "Nauru",
    value: "NR",
    phoneCode: "+674",
    currency: "AUD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Nepal",
    value: "NP",
    phoneCode: "+977",
    currency: "NPR",
    onramp: Onramps.None,
  },
  {
    label: "Netherlands",
    value: "NL",
    phoneCode: "+31",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "New Zealand",
    value: "NZ",
    phoneCode: "+64",
    currency: "NZD",
    onramp: Onramps.Onramp,
  },
  {
    label: "Nicaragua",
    value: "NI",
    phoneCode: "+505",
    currency: "NIO",
    onramp: Onramps.None,
  },
  {
    label: "Niger",
    value: "NE",
    phoneCode: "+227",
    currency: "XOF",
    onramp: Onramps.None,
  },
  {
    label: "Nigeria",
    value: "NG",
    phoneCode: "+234",
    currency: "NGN",
    onramp: Onramps.None,
  },
  {
    label: "North Korea",
    value: "KP",
    phoneCode: "+850",
    currency: "KPW",
    onramp: Onramps.None,
  },
  {
    label: "Norway",
    value: "NO",
    phoneCode: "+47",
    currency: "NOK",
    onramp: Onramps.Onramp,
  },
  {
    label: "Oman",
    value: "OM",
    phoneCode: "+968",
    currency: "OMR",
    onramp: Onramps.None,
  },
  {
    label: "Pakistan",
    value: "PK",
    phoneCode: "+92",
    currency: "PKR",
    onramp: Onramps.None,
  },
  {
    label: "Palestine",
    value: "PS",
    phoneCode: "+970",
    currency: "ILS",
    onramp: Onramps.None,
  },
  {
    label: "Panama",
    value: "PA",
    phoneCode: "+507",
    currency: "PAB",
    onramp: Onramps.None,
  },
  {
    label: "Papua New Guinea",
    value: "PG",
    phoneCode: "+675",
    currency: "PGK",
    onramp: Onramps.None,
  },
  {
    label: "Paraguay",
    value: "PY",
    phoneCode: "+595",
    currency: "PYG",
    onramp: Onramps.None,
  },
  {
    label: "Peru",
    value: "PE",
    phoneCode: "+51",
    currency: "PEN",
    onramp: Onramps.None,
  },
  {
    label: "Philippines",
    value: "PH",
    phoneCode: "+63",
    currency: "PHP",
    onramp: Onramps.None,
  },
  {
    label: "Poland",
    value: "PL",
    phoneCode: "+48",
    currency: "PLN",
    onramp: Onramps.Onramp,
  },
  {
    label: "Portugal",
    value: "PT",
    phoneCode: "+351",
    currency: "EUR",
    onramp: Onramps.Onramp,
  },
  {
    label: "Qatar",
    value: "QA",
    phoneCode: "+974",
    currency: "QAR",
    onramp: Onramps.None,
  },
  {
    label: "Romania",
    value: "RO",
    phoneCode: "+40",
    currency: "RON",
    onramp: Onramps.None,
  },
  {
    label: "Russia",
    value: "RU",
    phoneCode: "+7",
    currency: "RUB",
    onramp: Onramps.None,
  },
  {
    label: "Rwanda",
    value: "RW",
    phoneCode: "+250",
    currency: "RWF",
    onramp: Onramps.None,
  },
  {
    label: "Samoa",
    value: "WS",
    phoneCode: "+685",
    currency: "WST",
    onramp: Onramps.None,
  },
  {
    label: "Saudi Arabia",
    value: "SA",
    phoneCode: "+966",
    currency: "SAR",
    onramp: Onramps.None,
  },
];

export const onrampCurrencyCodes = {
  INR: 1,
  TRY: 2,
  AED: 3,
  MXN: 4,
  VND: 5,
  NGN: 6,
  BRL: 7,
  PEN: 8,
  COP: 9,
  CLP: 10,
  PHP: 11,
  EUR: 12,
  IDR: 14,
  GHS: 15,
  RAND: 16,
  USD: 21,
  THB: 27,
  ARS: 29,
  EGP: 31,
  LKR: 32,
};
